function [result,pixcoord] = cnr(inputfl,viewslice,k_slice,signalpts,bgcorners)
%% result = cnr(inputfl,viewslice,k_slice,signalpts,bgcorners)
% ------------------------------------------
% FILE   : cnr.m
% AUTHOR : Andy Shieh, School of Physics, The University of Sydney
% DATE   : 2013-01-31  Created
% ------------------------------------------
% PURPOSE
%   Calculate the contrast-to-noise ratio of the Metaimage files in the input
%   file list, output the result in a vector. A 2D background region with homogeneous
%   intensity, and a point of signal is chosen. The CNR is calculated by
%   the difference between the signal intensity and the mean of the
%   background, divided by the standard deviation of the background area.
%   The code assumes all the input files correspond to the same scan and same phase.
%   The code has to be executed at the directory containing the input
%   files.
%   Supports only mha files generated by rtk related modules.
%
%   [result,pixcoord] = cnr(inputfl,viewslice,k_slice,signalpts,bgcorners)
% ------------------------------------------
% INPUT
%   inputfl:        The input file list (can be obtained using ls('*.mha'))
%   viewslice:      Input 'axial','coronal', or 'sagittal' for the
%                   corresponding view.
%   k_slice:        The particular axial/coronal/sagittal slice to use.
%   signalpts:      The pixel coordinate of the signal in the format of
%                   [pointx,pointy]. The user can also input empty matrix
%                   '[]' for this field, and the code will display the
%                   particular slice, so the user can use ginput to select
%                   the corner manually. Multiple points can also be input
%                   - the signal intensity will be taken as the mean. The
%                   format would be [pt1x,pt1y;pt2x,pt2y;...]
%   bgcorners:      The pixel coordinates of the two corners of the background
%                   rectangle used to calculate the SNR, in the format of
%                   [corner1x,corner1y; corner2x,corner2y]. The user can
%                   also input empty matrix '[]' for this field, and the
%                   code will display the particular slice, so the user can
%                   use ginput to select the corner manually.
% ------------------------------------------
% OUTPUT
%   result:         The results in a vector corresponding to each file.
%   pixcoord:       The pixel coordinates of the points used in the format of
%                   [signalx,signaly; corner1x,corner1y; corner2x,corner2y]

%% Promt the user if no corner information is input

switch viewslice
    case 'axial'
        pmvector = [1 3 2];
    case 'coronal'
        pmvector = [1 2 3];
    case 'sagittal'
        pmvector = [3 2 1];
    otherwise
        error('ERROR: Please input either "axial", "coronal", or "sagittal" for the viewslice field');
        return;
end

nfile = size(inputfl);  nfile = nfile(1);
[info,M] = MhaRead(inputfl(1,:));
M = permute(M,pmvector);
M = M(:,:,k_slice);

if isequal(signalpts,[])
    imagesc(M'); colormap gray
    input('Please zoom in to the region of interest before continuing to make point selecting easier. Press "Enter" to continue:');
    disp('Please locate the signal. The average intensity will be used if multiple points are selected. Press "Enter" when finished.');
    signalpts = ginput;
end
signalpts = round(signalpts);
nsignal = size(signalpts);  nsignal = nsignal(1);

if isequal(bgcorners,[])
    imagesc(M'); colormap gray
    input('Please zoom in to the region of interest before continuing to make point selecting easier. Press "Enter" to continue:');
    disp('Please locate the two background corners.');
    bgcorners = ginput(2);
end
bgcorners = round(bgcorners);

pixcoord = [signalpts; bgcorners];

%% Loop through each file
% Derive the region of interest
xrange = min(bgcorners(1,1),bgcorners(2,1)):max(bgcorners(1,1),bgcorners(2,1));
yrange = min(bgcorners(1,2),bgcorners(2,2)):max(bgcorners(1,2),bgcorners(2,2));

result = zeros(nfile,1);

for k = 1:nfile
    R = M(xrange,yrange);
    I = 0;
    for k_sig = 1:nsignal
        I = I + M(signalpts(k,1),signalpts(k,2));
    end
    I = I/nsignal;
    result(k) = (I - mean(R(:))) / std(R(:));
    
    if k < nfile
        [info,M] = MhaRead(inputfl(k+1,:));
        M = permute(M,pmvector);
        M = M(:,:,k_slice);
    end
end

return