function [result,pixcoord] = cr(inputfl,viewslice,k_slice,signalpts,bgcorners)
%% result = cr(inputfl,viewslice,k_slice,signalpts,bgcorners)
% ------------------------------------------
% FILE   : cr.m
% AUTHOR : Andy Shieh, School of Physics, The University of Sydney
% DATE   : 2013-01-31  Created
%          2013-02-20  Auto mode supported
%          2013-03-06  Too messy. Need to rewrite this sometime. Use
%          crmarker.m for calculating CR using marker.
% ------------------------------------------
% PURPOSE
%   Calculate the contrast ratio of the Metaimage files in the input
%   file list, output the result in a vector. A 2D background region with homogeneous
%   intensity, and a point of signal is chosen. The CNR is calculated by
%   the difference between the signal intensity and the mean of the
%   background, divided by the standard deviation of the background area.
%   The code assumes all the input files correspond to the same scan and same phase.
%   The code has to be executed at the directory containing the input
%   files.
%   Supports only mha files generated by rtk related modules.
%
%   [result,pixcoord] = cr(inputfl,viewslice,k_slice,signalpts,bgcorners)
% ------------------------------------------
% INPUT
%   inputfl:        The input file list (can be obtained using ls('*.mha'))
%   viewslice:      Input 'axial','coronal', or 'sagittal' for the
%                   corresponding view.
%   k_slice:        The particular axial/coronal/sagittal slice to use. If
%                   the user input 'auto' for this field, the code will
%                   look for the particular slice where a point like object
%                   with high intensity exists (used for calculating cr
%                   with marker). In that case the user should just input
%                   the empty matrix "[]" for signalpts. 
%   signalpts:      The pixel coordinate of the signal in the format of
%                   [pointx,pointy]. The user can also input empty matrix
%                   '[]' for this field, and the code will display the
%                   particular slice, so the user can use ginput to select
%                   the corner manually. Multiple points can also be input
%                   - the signal intensity will be taken as the mean. The
%                   format would be [pt1x,pt1y;pt2x,pt2y;...]
%                   If "auto" mode is on, the user need to input 2 3D
%                   coordinates specifying the two corners of a cube within
%                   which the code will look for the marker (in RTK dimension). 
%                   If the empty matrix is input instead, the code will prompt the user
%                   to select it in an axial and coronal view.
%   bgcorners:      The pixel coordinates of the two corners of the background
%                   rectangle used to calculate the SNR, in the format of
%                   [corner1x,corner1y; corner2x,corner2y]. The user can
%                   also input empty matrix '[]' for this field, and the
%                   code will display the particular slice, so the user can
%                   use ginput to select the corner manually.
% ------------------------------------------
% OUTPUT
%   result:         The results in a vector corresponding to each file.
%   pixcoord:       The pixel coordinates of the points used in the format of
%                   [signalx,signaly; corner1x,corner1y;
%                   corner2x,corner2y]. If "auto" mode is on, it will only
%                   output the 3D coordinate of the marker position for
%                   each file.

%%

switch viewslice
    case 'axial'
        pmvector = [1 3 2];
    case 'coronal'
        pmvector = [1 2 3];
    case 'sagittal'
        pmvector = [3 2 1];
    otherwise
        error('ERROR: Please input either "axial", "coronal", or "sagittal" for the viewslice field');
        return;
end

nfile = size(inputfl);  nfile = nfile(1);
[info,M] = MhaRead(inputfl(1,:));

if ~strcmp(k_slice,'auto')
    M = permute(M,pmvector);
    M = M(:,:,k_slice);
    
    if isequal(signalpts,[])
        imagesc(M'); colormap gray
        input('Please zoom in to the region of signal. Press "Enter" to continue:');
        disp('Please locate the signal. The average intensity will be used if multiple points are selected. Press "Enter" when finished.');
        signalpts = ginput;
    end
    signalpts = round(signalpts);
    nsignal = size(signalpts);  nsignal = nsignal(1);
    
    if isequal(bgcorners,[])
        imagesc(M'); colormap gray
        input('Please zoom in to the region of background. Press "Enter" to continue:');
        disp('Please locate the two background corners.');
        bgcorners = ginput(2);
    end
    bgcorners = round(bgcorners);
    
    pixcoord = [signalpts; bgcorners];
    
    % Derive the region of interest
    xrange = min(bgcorners(1,1),bgcorners(2,1)):max(bgcorners(1,1),bgcorners(2,1));
    yrange = min(bgcorners(1,2),bgcorners(2,2)):max(bgcorners(1,2),bgcorners(2,2));
    
    result = zeros(nfile,1);
    
    for k = 1:nfile
        R = M(xrange,yrange);
        I = 0;
        for k_sig = 1:nsignal
            I = I + M(signalpts(k,1),signalpts(k,2));
        end
        I = I/nsignal;
        result(k) = (I - mean(R(:))) / I;
        
        if k < nfile
            [info,M] = MhaRead(inputfl(k+1,:));
            M = permute(M,pmvector);
            M = M(:,:,k_slice);
        end
    end
    
else   % Auto mode
    
    if isequal(signalpts,[])
        imagesc(M(:,:,end/2)'); colormap gray
        input('Please zoom in to the region of signal. Press "Enter" to continue:');
        disp('Please locate the two corners of the region containing marker motion in coronal view.');
        roi_c = ginput(2);
        M = permute(M,[1 3 2]);
        imagesc(M(:,:,end/2)'); colormap gray
        input('Please zoom in to the region of background. Press "Enter" to continue:');
        disp('Please locate the two corners of the region containing marker motion in axial view.');
        roi_a = ginput(2);
        M = permute(M,[1 3 2]);
        roi = [min(roi_c(:,1)),min(roi_c(:,2)),min(roi_a(:,2));max(roi_c(:,1)),max(roi_c(:,2)),max(roi_a(:,2))];
    else
        roi = [min(signalpts(:,1)),min(signalpts(:,2)),min(signalpts(:,3));max(signalpts(:,1)),max(signalpts(:,2)),max(signalpts(:,3))];
    end
    roi = round(roi);
    
    M_tmp = permute(M,pmvector);
    
    if isequal(bgcorners,[])
        imagesc(M_tmp(:,:,end/2)'); colormap gray
        input('Please zoom in to the region of interest before continuing to make point selecting easier. Press "Enter" to continue:');
        disp('Please locate the two background corners.');
        bgcorners = ginput(2);
    end
    bgcorners = round(bgcorners);
    
    % Derive the background region
    bgx = min(bgcorners(1,1),bgcorners(2,1)):max(bgcorners(1,1),bgcorners(2,1));
    bgy = min(bgcorners(1,2),bgcorners(2,2)):max(bgcorners(1,2),bgcorners(2,2));
    
    result = zeros(nfile,1);
    for k = 1:nfile
        M_roi = M(roi(1,1):roi(2,1),roi(1,2):roi(2,2),roi(1,3):roi(2,3));
        I = max(M_roi(:));
        
        tag = 0;
        for kx = roi(1,1):roi(2,1)
            for ky = roi(1,2):roi(2,2)
                for kz = roi(1,3):roi(2,3)
                    if M(kx,ky,kz) == I
                        signalpts(k,:) = [kx,ky,kz];
                        tag = 1;
                        break;
                    end
                end
                if tag == 1; break; end
            end
            if tag == 1; break; end
        end
        pixcoord = signalpts;

        M_tmp = permute(M,pmvector);
        switch viewslice
            case 'coronal'
                bgslice = kz;
            case 'axial'
                bgslice = ky;
            case 'sagittal'
                bgslice = kz;
            otherwise
                error('ERROR: Please input either "axial", "coronal", or "sagittal" for the viewslice field');
                return;
        end
        
        R = M_tmp(:,:,bgslice);
        R = R(bgx,bgy);
        result(k) = (I - mean(R(:))) / I;
        
        if k < nfile
            [info,M] = MhaRead(inputfl(k+1,:));
        end
    end
    
end

return