function [prof,pixcoord] = linprof(inputfl,viewslice,k_slice,endpts,mfsize)
%% [prof,pixcoord] = linprof(inputfl,viewslice,k_slice,endpts,mfsize)
% ------------------------------------------
% FILE   : linprof.m
% AUTHOR : Andy Shieh, School of Physics, The University of Sydney
% DATE   : 2013-01-26  Created
% ------------------------------------------
% PURPOSE
%   Calculate the linear profile of along the line specified by two
%   endpoints in the particular slice of the metaimage file.
%   The code has to be executed at the directory containing the input
%   files.
%   Supports only mha files generated by rtk related modules.
%
%   prof = linprof(inputfl,viewslice,k_slice,endpts)
%   [prof,pixcoord] = linprof(inputfl,viewslice,k_slice,endpts)
%   prof = linprof(inputfl,viewslice,k_slice,endpts,mfsize)
%   [prof,pixcoord] = linprof(inputfl,viewslice,k_slice,endpts,mfsize)
% ------------------------------------------
% INPUT
%   inputfl:        The input file list (can be obtained using ls('*.mha'))
%   viewslice:      Input 'axial','coronal', or 'sagittal' for the
%                   corresponding view.
%   k_slice:        The particular axial/coronal/sagittal slice to use. If
%                   range of numbers are given, the linear profile will be
%                   given as the mean of the results obtained from these
%                   slices.
%   endpts:         The pixel coordinates of the two end points of the
%                   line used to calculate the linear profile, in the format of
%                   [endpt1x,endpt2y;endpt2x,endpt2y]. The user can
%                   also input empty matrix '[]' for this field, and the
%                   code will display the particular slice, so the user can
%                   use ginput to select the endpoints manually.
%   mfsize:         (Optional) If the user enter a 2*1 vector of the size
%                   of a median filter, the code applys the filter to the
%                   slice before obtaining the linear profile. If this
%                   field is skipped, no filtering will be performed.
% ------------------------------------------
% OUTPUT
%   prof:           The results in a matrix, with each row representing the
%                   profile obtained from the corresponding file.
%   pixcoord:       The pixel coordinates used in the format of 
%                   [point1x,point1y; point2x,point2y; ...]

%% Promt the user if no corner information is input

switch viewslice
    case 'axial'
        pmvector = [1 3 2];
    case 'coronal'
        pmvector = [1 2 3];
    case 'sagittal'
        pmvector = [3 2 1];
    otherwise
        error('ERROR: Please input either "axial", "coronal", or "sagittal" for the viewslice field');
        return;
end

if nargin >= 5
    if length(mfsize) ~= 2
        error('ERROR: Incorrect median filter size.');
    end
end

nfile = size(inputfl);  nfile = nfile(1);
[info,M] = MhaRead(inputfl(1,:));
M = permute(M,pmvector);
M_mean = 0;
for s = 1:length(k_slice)
    if nargin >= 5
        M(:,:,k_slice(s)) = medfilt2(M(:,:,k_slice(s)),mfsize);
    end
    M_mean = M_mean + M(:,:,k_slice(s));
end
M_mean = M_mean / length(k_slice);

Msize = size(M);    nx = Msize(1);  ny = Msize(2);
[x0,y0] = meshgrid(1:nx,1:ny);

if isequal(endpts,[])
    imagesc(M_mean'); colormap gray
    input('Please zoom in to the region of interest before continuing to make point selecting easier. Press "Enter" to continue:');
    disp('Please locate the two endpoints.');
    endpts = ginput(2);
end

% endpts = round(endpts);

%% Loop through each file
% Derive the line
%npt = round(max(abs(endpts(2,2) - endpts(1,2)),abs(endpts(2,1) - endpts(1,1)))) + 1;
npt = round(sqrt((endpts(2,1)-endpts(1,1))^2 + (endpts(2,2)-endpts(1,2))^2)) + 1;
x = linspace(endpts(1,1),endpts(2,1),npt);
y = linspace(endpts(1,2),endpts(2,2),npt);
% x = round(x);   y = round(y);
[xx,yy] = meshgrid(x,y);

prof = zeros(nfile,npt);

for k = 1:nfile
    
    M_mean = interp2(x0,y0,M_mean',xx,yy);
    prof(k,:) = diag(M_mean);
    
%     for r = 1:npt
%         prof(k,r) = M_mean(x(r),y(r));
%     end
    
    if k < nfile
        [info,M] = MhaRead(inputfl(k+1,:));
        M = permute(M,pmvector);
        M_mean = 0;
        for s = 1:length(k_slice)
            if nargin >= 5
                M(:,:,k_slice(s)) = medfilt2(M(:,:,k_slice(s)),mfsize);
            end
            M_mean = M_mean + M(:,:,k_slice(s));
        end
        M_mean = M_mean / length(k_slice);
    end
end

pixcoord = [x',y'];

return
    

