function [result,pixcoord] = snr(inputfl,viewslice,k_slice,corners)
%% result = snr(inputfl,viewslice,k_slice,corners)
% ------------------------------------------
% FILE   : snr.m
% AUTHOR : Andy Shieh, School of Physics, The University of Sydney
% DATE   : 2013-01-25  Created
% ------------------------------------------
% PURPOSE
%   Calculate the signal-to-noise ratio of the Metaimage files in the input
%   file list, output the result in a vector. A 2D region with homogeneous
%   intensity is chosen, and the SNR is calculated by the mean divided by
%   the standard deviation of that area. The code assumes all the input
%   files correspond to the same scan and same phase.
%   The code has to be executed at the directory containing the input
%   files.
%   Supports only mha files generated by rtk related modules.
%
%   snrvector = snr(inputfl,viewslice,k_slice,corners)
% ------------------------------------------
% INPUT
%   inputfl:        The input file list (can be obtained using ls('*.mha'))
%   viewslice:      Input 'axial','coronal', or 'sagittal' for the
%                   corresponding view.
%   k_slice:        The particular axial/coronal/sagittal slice to use.
%   corners:        The pixel coordinates of the two corners of the
%                   rectangle used to calculate the SNR, in the format of
%                   [corner1x,corner1y; corner2x,corner2y]. The user can
%                   also input empty matrix '[]' for this field, and the
%                   code will display the particular slice, so the user can
%                   use ginput to select the corner manually.
% ------------------------------------------
% OUTPUT
%   result:         The results in a vector corresponding to each file.
%   pixcoord:       The pixel coordinates of the corners in the format of
%                   [corner1x,corner1y; corner2x,corner2y]

%% Promt the user if no corner information is input

switch viewslice
    case 'axial'
        pmvector = [1 3 2];
    case 'coronal'
        pmvector = [1 2 3];
    case 'sagittal'
        pmvector = [3 2 1];
    otherwise
        error('ERROR: Please input either "axial", "coronal", or "sagittal" for the viewslice field');
        return;
end

nfile = size(inputfl);  nfile = nfile(1);
[info,M] = MhaRead(inputfl(1,:));
M = permute(M,pmvector);
M = M(:,:,k_slice);

if isequal(corners,[])
    imagesc(M'); colormap gray
    input('Please zoom in to the region of interest before continuing to make point selecting easier. Press "Enter" to continue:');
    disp('Please locate the two corners.');
    corners = ginput(2);
end

corners = round(corners);
pixcoord = corners;

%% Loop through each file
% Derive the region of interest
xrange = min(corners(1,1),corners(2,1)):max(corners(1,1),corners(2,1));
yrange = min(corners(1,2),corners(2,2)):max(corners(1,2),corners(2,2));

result = zeros(nfile,1);

for k = 1:nfile
    R = M(xrange,yrange);
    result(k) = mean(R(:)) / std(R(:));
    
    if k < nfile
        [info,M] = MhaRead(inputfl(k+1,:));
        M = permute(M,pmvector);
        M = M(:,:,k_slice);
    end
end

return
    

