function result = snr3(inputfl,corners)
%% result = snr3(inputfl,corners)
% ------------------------------------------
% FILE   : snr3.m
% AUTHOR : Andy Shieh, School of Physics, The University of Sydney
% DATE   : 2013-01-28  Created
% ------------------------------------------
% PURPOSE
%   Calculate the 3D signal-to-noise ratio of the Metaimage files in the input
%   file list, output the result in a vector. A 3D region with homogeneous
%   intensity is chosen, and the SNR is calculated by the mean divided by
%   the standard deviation of that region. The code assumes all the input
%   files correspond to the same scan and same phase.
%   The code has to be executed at the directory containing the input
%   files.
%   Supports only mha files generated by rtk related modules.
%
%   snrvector = snr3(inputfl,corners)
% ------------------------------------------
% INPUT
%   inputfl:        The input file list (can be obtained using ls('*.mha'))
%   corners:        The pixel coordinates of the two corners of the
%                   cube used to calculate the SNR, in the format of
%                   [corner1x,corner1z,corner1y; corner2x,corner2z,corner2y].
% ------------------------------------------

%%

nfile = size(inputfl);  nfile = nfile(1);
[info,M] = MhaRead(inputfl(1,:));

corners = round(corners);

% Derive the region of interest
xrange = min(corners(1,1),corners(2,1)):max(corners(1,1),corners(2,1));
zrange = min(corners(1,2),corners(2,2)):max(corners(1,2),corners(2,2));
yrange = min(corners(1,3),corners(2,3)):max(corners(1,3),corners(2,3));

result = zeros(nfile,1);

for k = 1:nfile
    R = M(xrange,zrange,yrange);
    result(k) = mean(R(:)) / std(R(:));
    
    if k < nfile
        [info,M] = MhaRead(inputfl(k+1,:));
    end
end

return
    

