function WriteAngles2ElektaXML(in,outputFile,U,V)
%% WriteAngles2ElektaXML(in,outputFile)
% ------------------------------------------
% FILE   : WriteAngles2ElektaXML.m
% AUTHOR : Andy Shieh, School of Physics, The University of Sydney
% DATE   : 2015-06-17  Created.
% ------------------------------------------
% PURPOSE
%   Generate Elekta XML files from a series a angle files.
% ------------------------------------------
% INPUT
%   in:         Can be used in two ways:
%               1. A vector of angle values
%               2. The directory path to .angle files
%   outputFile: The output xml file name.
%   U:          If a global u offset value is used, input it as U.
%   V:          If a global v offset value is used, input it as V.

%% Default

if nargin < 1
    in = pwd;
end;

if nargin < 2
    outputFile = fullfile(pwd,'ElektaGeometry.xml');
end;

if nargin < 3
    U = 0;
end

if nargin < 4
    V = 0;
end

%% Read angles

if ischar(in)   % Read from files
    if exist('lscp.m') == 2
        fl = lscp(fullfile(in,'Angle*'));
    else
        fl = ls(fullfile(in,'Angle*'));
    end
    NProj = size(fl,1);
    tag_UID = 'ProjectionDataFile=';
    tag_angle = 'Angle=';
    tag_u = 'U_centre=';
    tag_v = 'V_centre=';
    tag_Delta = 'DeltaMS=';
    tag_Status = 'Status=';
    
    for k = 1:NProj
        fid = fopen(fl(k,:));
        cond = true;
        while cond
            tline = fgetl(fid);
            cond = ischar(tline);
            if length(tline) > length(tag_UID) && strcmpi(tline(1:length(tag_UID)),tag_UID)
                seq(k) = str2double(tline(length(tag_UID)+1:length(tag_UID)+5));
                if k == 1
                    UID = tline(length(tag_UID)+7:end-4);
                end
            elseif length(tline) > length(tag_angle) && strcmpi(tline(1:length(tag_angle)),tag_angle)
                angles(k) = str2double(tline(length(tag_angle)+1:end));
            elseif length(tline) > length(tag_u) && strcmpi(tline(1:length(tag_u)),tag_u)
                u(k) = str2double(tline(length(tag_u)+1:end));
            elseif length(tline) > length(tag_v) && strcmpi(tline(1:length(tag_v)),tag_v)
                v(k) = str2double(tline(length(tag_v)+1:end));
            elseif length(tline) > length(tag_Delta) && strcmpi(tline(1:length(tag_Delta)),tag_Delta)
                DeltaMS(k) = str2double(tline(length(tag_Delta)+1:end));
            elseif length(tline) > length(tag_Status) && strcmpi(tline(1:length(tag_Status)),tag_Status)
                Status(k) = str2double(tline(length(tag_Status)+1:end)) > 0;
            end
        end
        fclose(fid);
    end
else    % Angle vector
    NProj = length(in);
    seq = 1:NProj;
    UID = 'unknown';
    angles = in;
    if length(U) == NProj
        u = U;
    elseif length(U) == 1
        u = U * ones(size(in));
    else
        error('ERROR: The length of u must either be one or the same as the number of angular values.');
    end
    if length(V) == NProj
        v = V;
    elseif length(V) == 1
        v = V * ones(size(in));
    else
        error('ERROR: The length of v must either be one or the same as the number of angular values.');
    end
    DeltaMS = ones(size(in));
    Status = false(size(in));
end

%% Write to xml files

fid = fopen(outputFile,'w');

fprintf(fid,'<?xml version="1.0" encoding="utf-8"?>\n');
fprintf(fid,'<ProjectionSet>\n');
fprintf(fid,'  <!--Do not edit this file.-->\n');
fprintf(fid,'  <Image>\n');
fprintf(fid,'    <Width>512</Width>\n');
fprintf(fid,'    <Height>512</Height>\n');
fprintf(fid,'    <Depth>16</Depth>\n');
fprintf(fid,'    <DicomUID>0.0.0.0.0.0</DicomUID>\n');
fprintf(fid,'    <AbsoluteTableLatPosIEC1217_MM>-2</AbsoluteTableLatPosIEC1217_MM>\n');
fprintf(fid,'    <AbsoluteTableLongPosIEC1217_MM>639.7</AbsoluteTableLongPosIEC1217_MM>\n');
fprintf(fid,'    <AbsoluteTableVertPosIEC1217_MM>-230.6</AbsoluteTableVertPosIEC1217_MM>\n');
fprintf(fid,'  </Image>\n');

fprintf(fid,'  <Frames>\n');

for k = 1:NProj;
    if Status(k)
        str_inactive = 'True';
    else
        str_inactive = 'False';
    end
    
    fprintf(fid,'    <Frame>\n');
    fprintf(fid,'      <Seq>%d</Seq>\n',seq(k));
    fprintf(fid,'      <DeltaMs>%f</DeltaMs>\n',DeltaMS(k));
    fprintf(fid,'      <GantryAngle>%f</GantryAngle>\n',angles(k));
    fprintf(fid,'      <UCentre>%f</UCentre>\n',u(k));
    fprintf(fid,'      <VCentre>%f</VCentre>\n',v(k));
    fprintf(fid,'      <Inactive>%s</Inactive>\n',str_inactive);
    fprintf(fid,'    </Frame>\n');
end

fprintf(fid,'  </Frames>\n');
fprintf(fid,'</ProjectionSet>');

fclose(fid);

return;