function img_out = dvfWarpImg(header,img,dvf,xx,yy,zz)
%% img_out = dvfWarpImg(header,img,dvf,xx,yy,zz)
% ------------------------------------------
% FILE   : dvfWarpImg.m
% AUTHOR : Andy Shieh, ACRF Image X Institute, The University of Sydney
% DATE   : 2019-02-16 Created.
% ------------------------------------------
% PURPOSE
%  Warp image using DVF.
% ------------------------------------------
% INPUT
%   header:         The MHA header of the input image.
%   img:            The original image 3D matrix to be warped.
%   dvf:            The DVF which will be used to warp the image. Note that
%                   to relationship between the warped and original image
%                   is:
%                   img_out(x,y,z) = img(x+dvf_x,y+dvf_y,z+dvf_z)
%   xx,yy,zz:       Default: no need to enter
%                   To provide pre-generated meshgrid to save computation
%                   time.
%                   Can be generated by:
%                   [xx,yy,zz] = meshgrid(1:size(img,1),1:size(img,2),1:size(img,3));
%
% OUTPUT
%   img_out:        The warped 3D image.

%% Input check
img = single(img);
sImg = size(img);
sDVF = size(dvf);
if ~isequal(sImg,sDVF(1:3)) || sDVF(4) ~= 3
    error('The first three dimensions of img and dvf must be the same. dvf must has 3 components for each voxel.');
end

%% Calculation
% Create meshgrid
if nargin < 4
    [xx,yy,zz] = meshgrid(1:sImg(1),1:sImg(2),1:sImg(3));
end

% Meshgrid at query points
xq = xx + permute(dvf(:,:,:,1),[2 1 3]) / header.PixelDimensions(1);
yq = yy + permute(dvf(:,:,:,2),[2 1 3]) / header.PixelDimensions(2);
zq = zz + permute(dvf(:,:,:,3),[2 1 3]) / header.PixelDimensions(3);

img_out = interp3(xx,yy,zz,permute(img,[2 1 3]),xq,yq,zq,'linear');
img_out = permute(img_out,[2 1 3]);
img_out(isnan(img_out)) = 0;